feat(spices): add border style
leostera/minttea pull request #41
Opened 2024-03-11 20:24 UTC by ironmanvim

add border style utils to create borders

2024-03-14 09:56 UTC, leostera requested changes
Hi @ironmanvim! Thanks for the PR ✨ this looks great. Just some minor tweaks I think we want to have here and we should be good to merge :)

Tweaks:

* adding an explicit signature to the Border module with a `make` constructor function

* exposing predefined borders directly as values rather than through a function – so we don't need a `get_border` function

* add the border example to the `examples/README.md` file

How does this sound? Let me know if you have any questions 🙏🏼

2024-03-14 09:56 UTC, leostera commented on spices/spices.mli
> +val border : Border.t -> style -> style
**suggestion**. from looking at how we're using this call (`border (get_border Thick)`) I think we could just export predefined borders from the Border module and use them like this, without needing a `get_border` function:

```ocaml
let overlay_border fmt =
  Spices.(default |> border Border.double |> build) fmt
```

2024-03-14 09:56 UTC, leostera commented on spices/spices.mli
> +val border : Border.t -> style -> style
**fix**. let's add a signature for the Border module here, like:

```ocaml
module Border : sig
  type t

  val make : 
    ?bottom:string ->
    ?bottom_left:string ->
    ?bottom_right:string ->
    ?left:string ->
    ?middle:string ->
    ?middle_bottom:string ->
    ?middle_left:string ->
    ?middle_right:string ->
    ?middle_top:string ->
    ?right:string ->
    ?top:string ->
    ?top_left:string ->
    ?top_right:string ->
    unit ->
    t

  val normal : t
  val rounded : t
  (* other predefined borders here *)
end
```

2024-03-15 08:29 UTC, ironmanvim commented
@leostera Worked with the changes.

2024-03-16 13:57 UTC, leostera commented on spices/border.ml
> +    (_unit : unit) =
```suggestion
    () =
```

2024-03-16 13:59 UTC, leostera approved these changes
LGTM! 🚀

2024-03-16 13:59 UTC, merged

2024-03-16 14:00 UTC, leostera commented
Thanks a lot @ironmanvim! Super happy with this :)